run:
  timeout: 3m
  go: "1.20"

# This file contains only configs which differ from defaults.
# All possible options can be found here https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters-settings:
  cyclop:
    max-complexity: 30
    package-average: 10.0

  errcheck:
    check-type-assertions: true

  funlen:
    lines: 100
    statements: 50

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
            reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"
        - github.com/satori/go.uuid:
            recommendations:
              - github.com/google/uuid
            reason: "satori's package is not maintained"
        - github.com/gofrs/uuid:
            recommendations:
              - github.com/google/uuid
            reason: "see recommendation from dev-infra team: https://confluence.gtforge.com/x/gQI6Aw"

  govet:
    enable-all: true
    disable:
      - fieldalignment

    settings:
      shadow:
        strict: true

  nakedret:
    max-func-lines: 0

  nolintlint:
    allow-no-explanation: [funlen, gocognit, lll]
    require-explanation: false
    require-specific: true

  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx

  tenv:
    all: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gocritic
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - makezero
    - mirror
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
